### PR TITLE
Add ComponentUsage, MaterialType, and UnitType Enums as well as their Implementations

### PR DESCRIPTION
**Pull request by jth41**
Followup work from last meeting and answer to Issue #2. https://github.com/jth41/sbca-data-standard/issues/2

Implements a ComponentType Enum and UnitType properties on Components to identify the values used throughout the remainder of the file.

### CODE REVIEW

**Comment by ChrisGouldIs** [comment]
Are there benefits to calling out roof vs. floor for a truss? If a wood floor truss has steel webbing, is it a wood or steel floor truss? Should we also include components such as beams, posts, ledgers, joists, etc?

**Comment by KevinWitt77** [comment]
Truss type would certainly be a fact of the truss, so yes, I think there are benefits to having that in the data standard.  I have no idea if there is a different name for a wood floor truss with steel webs.  My thought on beams, posts, and ledgers would be yes, if it can be output to cut or assemble, we should include it in the data standard.

**Comment by ChrisGouldIs** [comment]
Let me clarify my question. Often, when we talk of wood roof or floor trusses, we are actually describing 3 distinct facts: usage, loading, and board orientation. However, we are seeing more and more cases of 4x trusses being used in roofing scenarios, and recently even a case of a roof truss extending into the structure to also form part of the floor, and thus needing both loading. Thus, I am proposing we clarify ComponentType so as to not blend 3 (or more) distinct facts into a single enumeration.

**Comment by jth41** [comment]
@ChrisGouldIs I see what you mean now. Take a look at what I divided that enum into in the latest commits to this PR. I changed it so Components have a list of `Usages` and `MaterialTypes` and Flattened the materials like we described in the previous meeting.

This should allow for Components made of multiple types of material and used in multiple structural systems.

Take a look and see what you think

**Comment by ChrisGouldIs** [comment]
I think this all looks good. I approve!

**Pull request merged**
